config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'

  	get 'posts/new'
	resources :posts do
		resources :answers
	end
  	root 'posts#index' ,as: 'home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
  	# render plain: params[:answer].inspect
  	@post = Post.find(params[:post_id])
  	@answer = @post.answers.create(answer_params)
  	redirect_to post_path(@post)
  end
  private def answer_params
  	params.require(:answer).permit(:fCODE,:fANSWER,:fTRUEFALSE)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name:'admin', password:'password',
  except: [:index,:show]
    @@count = 0
  
  def index
    
    if (@@count <= 4)
      @query = ActiveRecord::Base.connection.execute("select * from posts where status = 0 ORDER BY lower(hex(randomblob(16))) LIMIT 1 ")[0]
      @code = @query["code"]
      @question = @query["question"]
      @point = @query["bal"]
      @post = Post.where(id: @code)
      @answer = Answer.where(fCODE: @code)

      Post.where(:code => @code).first.update(:status => 1)
      @@count = @@count + 1    
    else
      @@count = 0
      Post.update_all(status: 0)
    end

      # @post = Post.all()
  end

  def new
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def create
  	@post = Post.new(post_params)
  	@post.save
  	redirect_to @post
  end

  private def post_params
  	params.require(:post).permit(:code,:question,:status,:bal)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<%= form_for :answer, url: answers_path do |f| %>
	<p>
		code<br>
		<%= f.text_field :code %>
	</p>

	<p>
		answer<br>
		<%= f.text_area :answer %>
	</p>

	<p>
		trueOrFalse<br>
		<%= f.text_field :truefalse %>
	</p>


	<p>
		<%= f.submit("ADD Answer") %>
	</p>

	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-bold">Who Wants to Be a Millionaire?</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-dark"><%= link_to 'Home Page',home_path %></span>
  </nav>
  <span class="p-2 text-dark"><%= link_to 'ADD Question',new_post_path %></span>
  
</div>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Question</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<p>
		code<br>
		<%= f.text_field :code %>
	</p>

	<p>
		question<br>
		<%= f.text_area :question %>
	</p>

	<p>
		status<br>
		<%= f.text_field :status %>
	</p>

	<p>
		point<br>
		<%= f.text_field :bal %>
	</p>

	<p>
		<%= f.submit("EDIT QUESTION") %>
	</p>

	<% end %>

app/views/posts/index.html.erb
<% begin %>
<%= @arr %>
<% @post.each do |p| %>
	<!-- <p><%= p.code %></p> -->
	<p><%= p.question %></p>

	<!-- <p><%= p.status %></p> -->
	<!-- <p><%= p.bal %></p> -->
	<% @answer.each do |answer| %>
	<% if answer.fTRUEFALSE == 0 %>
	<%= link_to answer.fANSWER, posts_path, data: { confirm: "your answer is false, your score is 0" } %>
	<br><br>
	<% else %>
		<%= link_to answer.fANSWER, posts_path, data: { confirm: "your answer is true, your score is #{p.bal}" } %>
		<br><br>
		<% end %>
	<% end %>

<% end %>

<%= link_to "Next Question>>", posts_path,:class =>'btn btn-warning' %>
<% rescue => e%>
    game end<br><br>
<% end %>

app/views/posts/new.html.erb
<h1>new#Question</h1>
<%= form_for :post, url: posts_path do |f| %>
	<p>
		code<br>
		<%= f.text_field :code %>
	</p>

	<p>
		question<br>
		<%= f.text_area :question %>
	</p>

	<p>
		status<br>
		<%= f.text_field :status %>
	</p>

	<p>
		point<br>
		<%= f.text_field :bal %>
	</p>

	<p>
		<%= f.submit("ADD QUESTION") %>
	</p>

	<% end %>

app/views/posts/show.html.erb
<p>code: <%= @post.code %></p>
<p>question: <%= @post.question %></p>
<p>status: <%= @post.status %></p>
<p>bal: <%= @post.bal %></p>

<%= link_to "Edit question", edit_post_path(@post), :class => 'btn btn-warning' %>
<hr>
	<% @post.answers.each do |answer| %>
		<p>code: <%= answer.fCODE %></p>
		<p>answer: <%= answer.fANSWER %></p>
		<p>trueOrFalse: <%= answer.fTRUEFALSE %></p>
	<% end %>
</hr>
<h1>Answers#new</h1>
<%= form_for ([@post, @post.answers.build])do |f| %>
	<p>
		code<br>
		<%= f.text_field :fCODE %>
	</p>

	<p>
		answer<br>
		<%= f.text_area :fANSWER %>
	</p>

	<p>
		trueOrFalse<br>
		<%= f.text_field :fTRUEFALSE %>
	</p>


	<p>
		<%= f.submit("ADD Answer") %>
	</p>

	<% end %>